- name: Install docker packages
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
    
  with_items:
    - ca-certificates
    - curl 
    - gnupg
    - lsb-release
    - apt-transport-https
  register: dependencies
  